"""
streamlit_app.py

Interactive Streamlit app for diabetes risk prediction and explainability.
"""

# import necessary libraries
# Standard library
import os

# Third-party libraries
import pandas as pd
import joblib
import shap
import streamlit as st
import streamlit.components.v1 as components


# ------------------------------------------------------
# Helper: Convert risk score into human-friendly category
# ------------------------------------------------------
def categorize_risk(score):
    """
    Converts a numeric probability (0–1) into a human-friendly category.
    Thresholds can be calibrated later.
    """
    if score < 0.33:
        return "Low"
    elif score < 0.66:
        return "Medium"
    else:
        return "High"


# ------------------------------------------------------
# Load model and scaler
# ------------------------------------------------------
MODELS_DIR = os.path.join(os.path.dirname(__file__), "..", "models")
model_path = os.path.join(MODELS_DIR, "final_model.pkl")
scaler_path = os.path.join(MODELS_DIR, "scaler.pkl")

model = joblib.load(model_path)
scaler = joblib.load(scaler_path)

# ------------------------------------------------------
# Streamlit UI — User Inputs
# ------------------------------------------------------
st.title("🩺 Diabetes Risk Prediction (XAI Enhanced)")

# Example input fields (modify based on your final input schema)
pregnancies = st.number_input("Pregnancies", 0, 20, 1)
glucose = st.number_input("Glucose", 0, 200, 120)
blood_pressure = st.number_input("Blood Pressure", 0, 150, 70)
skin_thickness = st.number_input("Skin Thickness", 0, 99, 20)
insulin = st.number_input("Insulin", 0, 900, 80)
bmi = st.number_input("BMI", 0.0, 70.0, 25.0)
dpf = st.number_input("Diabetes Pedigree Function", 0.0, 5.0, 0.5)
age = st.number_input("Age", 1, 120, 30)

# Organize into dataframe
input_df = pd.DataFrame([{
    "Pregnancies": pregnancies,
    "Glucose": glucose,
    "BloodPressure": blood_pressure,
    "SkinThickness": skin_thickness,
    "Insulin": insulin,
    "BMI": bmi,
    "DiabetesPedigreeFunction": dpf,
    "Age": age
}])

# ------------------------------------------------------
# Prediction Button
# ------------------------------------------------------
if st.button("Predict Risk"):

    # Scale input
    scaled = scaler.transform(input_df)

    # Probability (0–1)
    risk_score = model.predict_proba(scaled)[0][1]

    # Human-readable category
    risk_category = categorize_risk(risk_score)

    # Display results
    st.subheader("Prediction Result")
    st.write(f"**Risk Score:** {risk_score:.2f}")
    st.write(f"**Risk Category:** {risk_category}")

    # ------------------------------------------------------
    # Optional: Load SHAP Force Plot (generated by notebook)
    # ------------------------------------------------------
    RESULTS_DIR = os.path.join(os.path.dirname(__file__), "..", "results")
    force_file = os.path.join(RESULTS_DIR, "shap_force_idx_0.html")

    st.subheader("Explainability (SHAP Force Plot)")
    if os.path.exists(force_file):
        with open(force_file, "r", encoding="utf-8") as f:
            components.html(f.read(), height=400, scrolling=True)
    else:
        st.info("No SHAP force plot found. Run the XAI notebook to generate it.")
