# Milestone5_deployment/app/streamlit_app.py
import os
from pathlib import Path
import streamlit as st
import streamlit.components.v1 as components
import json

# ----------------------------
# Configuration / Project root
# ----------------------------
# Adjust this to your repo root if needed; this assumes this app file sits in
# Milestone5_deployment/app/ and results/ is at the repo root.
APP_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = APP_DIR.parents[1]  # two levels up -> repo root
RESULTS_DIR = PROJECT_ROOT / "results"
MODELS_DIR = PROJECT_ROOT / "models"

# Create results dir if missing (UI will show helpful text)
RESULTS_DIR.mkdir(parents=True, exist_ok=True)

# ----------------------------
# Helpers
# ----------------------------
def list_files(pattern):
    return sorted(list(map(Path, RESULTS_DIR.glob(pattern))))

def read_json(path):
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return None

def html_file_to_component(path, height=500):
    """Safely read an HTML file and return a components.html render call."""
    try:
        with open(path, "r", encoding="utf-8") as f:
            html = f.read()
        components.html(html, height=height, scrolling=True)
    except Exception as e:
        st.error(f"Failed to load HTML file {path.name}: {e}")

def show_file_download(path: Path):
    try:
        with open(path, "rb") as f:
            data = f.read()
        st.download_button(label=f"Download {path.name}", data=data, file_name=path.name)
    except Exception as e:
        st.warning(f"Unable to offer download for {path.name}: {e}")

# ----------------------------
# Page layout
# ----------------------------
st.set_page_config(page_title="Diabetes Risk — Explainability (XAI)", layout="wide")
st.title("Diabetes Risk — Explainability / XAI Viewer")
st.markdown(
    """
Use this page to inspect interactive explainability artifacts (SHAP force plots, LIME outputs) that
were generated by the `03_explainability.ipynb` notebook. If an artifact is missing, run the notebook
to regenerate it — artifacts are stored under `/results/`.
"""
)

# ----------------------------
# Sidebar: artifact lists & metadata
# ----------------------------
st.sidebar.header("Available artifacts")

# metadata (optional)
meta = read_json(RESULTS_DIR / "xai_metadata.json")
if meta:
    st.sidebar.subheader("XAI metadata")
    st.sidebar.write(f"Top features: {meta.get('top_features', [])}")
    st.sidebar.write(f"Representative cases: {meta.get('cases', [])}")

# list SHAP force HTMLs and LIME HTMLs
shap_htmls = list_files("shap_force*.html")
lime_htmls = list_files("lime_case_*.html")
pngs = list_files("*.png")  # optional static plots

st.sidebar.markdown(f"**SHAP interactive (HTML)**: {len(shap_htmls)}")
for p in shap_htmls:
    st.sidebar.write(p.name)

st.sidebar.markdown(f"**LIME interactive (HTML)**: {len(lime_htmls)}")
for p in lime_htmls:
    st.sidebar.write(p.name)

st.sidebar.markdown(f"**Static images** (PNG): {len(pngs)}")

# ----------------------------
# Main area: SHAP section
# ----------------------------
st.header("SHAP — Interactive Force Plots")
if shap_htmls:
    shap_choice = st.selectbox("Select a SHAP force HTML to view", [p.name for p in shap_htmls])
    selected = RESULTS_DIR / shap_choice
    st.subheader(f"Viewing: {shap_choice}")
    st.markdown("---")
    # Embed
    html_file_to_component(selected, height=600)
    # Download
    show_file_download(selected)
else:
    st.info(
        "No SHAP force HTML artifacts found in /results/. "
        "Run `03_explainability.ipynb` and rerun this app. "
        "Example filenames: shap_force_idx_0.html"
    )

# ----------------------------
# LIME section
# ----------------------------
st.header("LIME — Local Explanations (HTML)")
if lime_htmls:
    lime_choice = st.selectbox("Select a LIME HTML to view", [p.name for p in lime_htmls], key="lime")
    selected_lime = RESULTS_DIR / lime_choice
    st.subheader(f"Viewing: {lime_choice}")
    st.markdown("---")
    html_file_to_component(selected_lime, height=500)
    show_file_download(selected_lime)
else:
    st.info(
        "No LIME HTML artifacts found in /results/. "
        "Run the LIME cell in `03_explainability.ipynb` to generate files named `lime_case_<idx>.html`."
    )

# ----------------------------
# Optional: static SHAP/LIME images & metadata
# ----------------------------
st.header("Static visualizations & metadata")
if pngs:
    cols = st.columns(3)
    for i, p in enumerate(pngs):
        with cols[i % 3]:
            st.image(str(p), caption=p.name, use_column_width=True)
            show_file_download(p)
else:
    st.info("No static PNGs found in /results/. The notebook can optionally save summary plots as PNG for reports.")

# ----------------------------
# Advanced: quick inspect (raw JSON metadata)
# ----------------------------
with st.expander("Advanced: XAI metadata (raw)"):
    st.json(meta if meta else {"status": "no metadata found"})

# ----------------------------
# Footer / notes
# ----------------------------
st.markdown("---")
st.caption("If an artifact is missing: run `03_explainability.ipynb` (Milestone 3) to regenerate SHAP/LIME artifacts, then refresh this app.")
